version: '3'
services:
  ros:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        USER_NAME: ${USER_NAME:-0}
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    command: tail -f /dev/null
    volumes: 
      - ./CS4501-Labs:/home/${USER_NAME:-/../root/}/CS4501-Labs/
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - x11
    hostname: ros_docker
  novnc:  
    image: theasp/novnc:latest
    volumes: 
      - ./CS4501-Labs:/home/${USER_NAME:-/../root/}/CS4501-Labs/
    environment:
      - DISPLAY_WIDTH=800
      - DISPLAY_HEIGHT=600
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - x11
    hostname: novnc_docker
networks:
  x11:
